[package]
name = "audio"
version = "0.1.0"
authors = ["Kevin Berry <kpberry11@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
num = "*"
rustfft = "*"
wav = "*"
parry3d = "*"

[lib]
name = "audio"